allow-branch = ["master"]
sign-commit = false
sign-tag = false
push = true
publish = false
tag-message = "Release {{version}}"
pre-release-commit-message = "Release {{version}}"
pre-release-hook = ["cargo", "test", "--all", "--locked"]
pre-release-replacements = [
  { file = "CHANGELOG.md", search = "\\[Unreleased\\]", replace = "[{{version}}] - {{date}}", exactly = 1 },
  { file = "CHANGELOG.md", search = "<!-- next-header -->", replace = "<!-- next-header -->\n\n## [Unreleased]", exactly = 1, min = 0 },
]
tag-name = "v{{version}}"
